name: add-pr-label

on:
  pull_request:
    types: [opened, edited, closed, reopened, synchronize, assigned, unassigned, labeled, unlabeled, review_requested, review_request_removed, ready_for_review, converted_to_draft]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Add 'PLEASE ADD REVIEWS' label to current PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "Applying label to PR #${{ env.PR_NUMBER }}"
          # This POST call adds the label to the PR issue
          curl -X POST \
            -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ env.PR_NUMBER }}/labels \
            -d '{"labels": ["PLEASE ADD REVIEWS"]}'